version: '3.4'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '32411680'
      MYSQL_DATABASE: 'smarttbot'
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 3
  api:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on: 
      db:
        condition: service_healthy
    ports:
      - "3000:3000"